---
# tasks file for prelim
- name: create reporting folder
  delegate_to: "{{ report_server }}"
  file:
    path: "{{ report_dir}}/test.{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
    state: directory
  register: folder_info
  run_once: true
